version: "3.9"

services:
  hexlicsrv:
    container_name: hexlicsrv
    build:
      context: ./image
    restart: always
    environment:
      # === App ===
      LICENSE_HOST: reversing.example.com
      LICENSE_PORT: "65434"

      # === Release sync (GitHub Releases) ===
      # Enable sync with a GitHub Release
      # RELEASE_SYNC_ENABLED: "true"
      # Repository owner/name
      # GH_OWNER: RenardDev
      # GH_REPO: IDATeams
      # Release tag and display name
      # GH_RELEASE_TAG: hexlicsrv-snapshot
      # GH_RELEASE_NAME: HexLicSrv FS Snapshot
      # Host ID used in manifest.json (optional)
      # GH_HOST_ID: hexlicsrv
      # Chunk size (MB) when splitting the archive
      # GH_CHUNK_SIZE_MB: "49"
      # Token (PAT) required for upload/private release access
      # GH_TOKEN: github_pat_***

    volumes:
      - ./CA:/opt/hexlicsrv/CA
      - ./config:/opt/hexlicsrv/config
      - ./logs:/opt/hexlicsrv/logs
      - ./data:/opt/hexlicsrv/data

    ports:
      - "65434:65434"
