version: "3.9"

services:
  hexvault:
    container_name: hexvault
    build:
      context: ./image
    restart: always
    environment:
      # === App ===
      VAULT_HOST: reversing.example.com
      VAULT_PORT: "65433"

      # === Release sync (GitHub Releases) ===
      # RELEASE_SYNC_ENABLED: "true"
      # GH_OWNER: RenardDev
      # GH_REPO: IDATeams
      # GH_RELEASE_TAG: hexvault-snapshot
      # GH_RELEASE_NAME: HexVault FS Snapshot
      # GH_HOST_ID: hexvault
      # GH_CHUNK_SIZE_MB: "49"
      # GH_TOKEN: github_pat_***

    volumes:
      - ./CA:/opt/hexvault/CA
      - ./config:/opt/hexvault/config
      - ./logs:/opt/hexvault/logs
      - ./data:/opt/hexvault/data

    ports:
      - "65433:65433"
