
services:
  hexvault:
    container_name: hexvault
    build: ./image
    restart: always
    environment:
      SKIP_RECREATE_SCHEMA: N
      VAULT_HOST: reversing.example.com
    volumes:
      - ./data/CA/:/opt/hexvault/CA/
      - ./data/files/:/opt/hexvault/files/
    ports:
      - "65433:65433"
